# Hexo Configuration
# Site: wang-xin.cc
# Author: Wang Xin

# Site
title: Wang Xin
subtitle: 绉戞妧鍒涙柊 路 璁捐缇庡
description: 涓汉浣滃搧闆嗕笌鍗氬锛屼笓娉ㄤ簬鎶€鏈帰绱笌鍒涙剰瀹炵幇
author: Wang Xin
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://wang-xin.cc
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  newtab: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true

# Home page
index_generator:
  path: ""
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata
meta_generator: true

# Date / Time
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

# Pagination
per_page: 12
pagination_dir: page

# Include / Exclude
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repository: https://github.com/wangxin488324/wangxin488324.github.io.git
  branch: gh-pages

# Search
search:
  path: search.json
  field: post
  content: true
  template: false

# Sitemap
sitemap:
  path: sitemap.xml

